-- CreateTable
CREATE TABLE "GlobalState" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "lastSyncedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "remaining" INTEGER NOT NULL DEFAULT 1000
);
